[main]
font = FantasqueSansM Nerd Font:size=14.0
pad = 4x4
initial-window-mode = windowed

[colors-dark]
alpha = 1.0
foreground = d4be98
background = 26211f

cursor = 26211f d4be98

# Regular/Normal colors
regular0 = 322d2a
regular1 = e58273
regular2 = a9b665
regular3 = e8b770
regular4 = 7daea3
regular5 = d3869b
regular6 = 89b482
regular7 = d4be98

# Bright colors
bright0 = 7c6f64
bright1 = ea6962
bright2 = b8bb26
bright3 = e7b084
bright4 = 83a598
bright5 = d65d0e
bright6 = 8ec07c
bright7 = fbf1c7
