# -*- conf -*-

[main]
font = FantasqueSansM Nerd Font:size=14.0
pad = 4x4
initial-window-mode = windowed

[colors-dark]
alpha = 1.0
foreground = d4be98
background = 26211f

cursor = 26211f d4be98

# Regular/Normal colors
regular0 = 322d2a  # black
regular1 = e58273  # red (Pastel Terracotta)
regular2 = a9b665  # green (Pastel Sage Green)
regular3 = e8b770  # yellow (Pastel Warm Yellow)
regular4 = 7daea3  # blue (Pastel Soft Blue)
regular5 = d3869b  # magenta (Pastel Muted Pink/Lavender)
regular6 = 89b482  # cyan (Pastel Seafoam)
regular7 = d4be98  # white

# Bright colors
bright0 = 7c6f64   # bright black
bright1 = ea6962   # bright red
bright2 = b8bb26   # bright green
bright3 = e7b084   # bright yellow
bright4 = 83a598   # bright blue
bright5 = d65d0e   # bright magenta
bright6 = 8ec07c   # bright cyan
bright7 = fbf1c7   # bright white
