music_directory      "~/Music"
playlist_directory   "~/.config/mpd/playlists"
db_file              "~/.config/mpd/database"
log_file             "~/.config/mpd/log"
pid_file             "~/.config/mpd/pid"
state_file           "~/.config/mpd/state"

bind_to_address      "127.0.0.1"
port                 "6600"

# Audio Output (PulseAudio / PipeWire)
audio_output {
    type "pulse"
    name "Local PulseAudio / PipeWire"
}

decoder {
    plugin "wildmidi"
    enabled "no"
}

