music_directory      "~/Music"
playlist_directory   "~/.config/mpd/playlists"
db_file              "~/.config/mpd/database"
log_file             "~/.config/mpd/log"
pid_file             "~/.config/mpd/pid"
state_file           "~/.config/mpd/state"

bind_to_address      "127.0.0.1"
port                 "6600"

# audio_output {
#     type            "pipewire"
#     name            "PipeWire Output"
#     auto_resample   "no"
#     buffer_time     "100000"
# }

#audio_output {
#    type            "alsa"
#    name            "Kinera DAC"
#    device          "hw:2,0"
#    mixer_type      "none"
#    auto_resample   "no"
#    auto_channels   "no"
#    auto_format     "no"
#}

audio_output {
    type            "alsa"
    name            "void"
    device          "hw:1,0"
    mixer_type      "none"
    auto_resample   "no"
    auto_channels   "no"
    auto_format     "no"
}

