"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$nix_shell\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "fg:83a598" # Biru pastel Gruvbox
format = "[$path]($style) "

[username]
style_user = "fg:fabd2f bold" # Kuning hangat Gruvbox
style_root = "fg:fb4934 bold"
format = "[$user]($style) "
show_always = false

[hostname]
style = "fg:d3869b" # Ungu pastel Gruvbox
format = "@[$hostname]($style) "
disabled = false

[nix_shell]
format = "[$symbol($state)]($style) "
symbol = "❄️ "
style = "bold fg:83a598"
disabled = false

[character]
success_symbol = "[>](fg:b8bb26 bold)" # Hijau pastel Gruvbox
error_symbol = "[>](fg:fb4934 bold)"   # Merah pastel Gruvbox
vimcmd_symbol = "[<](fg:fabd2f bold)"

[git_branch]
format = "[$branch]($style)"
style = "fg:928374 bold" # Abu-abu/cokelat netral Gruvbox

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](fg:d65d0e) ($ahead_behind$stashed)]($style)"
style = "fg:83a598"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "fg:928374"

[cmd_duration]
format = "[$duration](fg:fabd2f) "

[python]
format = "[$virtualenv](fg:928374) "
detect_extensions = []
detect_files = []
