#!/bin/sh 

alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../../'
alias .4='cd ../../../../'

alias l='ls -lah'
alias la='ls -A'
alias ll='ls -l'
alias llah='ls -llah'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias cpwd='echo -n $(pwd) | wl-copy'

alias s='sudo'

alias r='rsync -avzP'
alias p='sudo pacman'
alias psyu='sudo pacman -Syu'
alias porp='sudo pacman -Rns $(pacman -Qdtq)'

alias v='nvim'
alias vim='nvim'
alias z='zeditor .'
alias art='php artisan'
alias d='docker'
alias dc='docker-compose'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'
alias dcl='docker-compose logs -f'

alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add .'
alias gc='git clone'
alias gcm='git commit -m'
alias gpush='git push'
alias gpull='git pull'
alias gf='git fetch'
alias gl='git log --oneline --graph --all'

alias myip='curl ifconfig.me && echo'
alias mirrorupd='sudo reflector --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist'
alias jctl='journalctl -p 3 -xb'

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'

alias vsrc='nvim ~/.zshrc'
alias valias='nvim ~/.config/aliases'

# Service
alias service='sudo systemctl' 
alias status='sudo systemctl status' 
alias start='sudo systemctl start' 
alias stop='sudo systemctl stop' 
alias restart='sudo systemctl restart' 
alias enable='sudo systemctl enable --now' 
alias disable='sudo systemctl disable --now' 

# Dotfiles management aliases
alias dot='cd ~/.config/dotfiles'
alias dots="make -C ~/.config/dotfiles"
alias dotl="make -C ~/.config/dotfiles link"
alias dotu="make -C ~/.config/dotfiles unlink"
alias dotr="make -C ~/.config/dotfiles relink"
alias dotc="make -C ~/.config/dotfiles check"

# encryption
alias gpgenc="gpg --symmetric --cipher-algo AES256"
alias gpgdec="gpg --decrypt"

# realpath, no link
alias nolink="find . -maxdepth 1 -type f -not -type l -exec realpath {} + 2>/dev/null"

# xbps things
alias xi="sudo xbps-install"
alias xr="sudo xbps-remove"
alias xq="xbps-query"
