#!/bin/sh

# Fuzzy finder project. Assumes anything that have '.git' 
# directory will be considered as a project things.

fp() {
    local project_dir session_name
    project_dir=$(fd '^\.git$' ~/ \
        --hidden --no-ignore --type d --prune \
        --exclude '{.cache,node_modules,.local,.tmux,.config/tmux/plugins*,.config/tmux/plugins/tmux-fzf}' \
        2>/dev/null --exec echo {//} | fzf --height 50% --layout=reverse --border)

    [ -z "$project_dir" ] && return

    session_name=$(basename "$project_dir" | tr '.:' '_')

    # cd into project directory and use abduco with the -A flag 
    # (-A creates the session if it doesn't exist, or attaches to it if it does)
    cd "$project_dir" && abduco -A "$session_name" 
}
