#!/bin/sh

xin() {
    xbps-query -Rs '*' | awk '$1 !~ /\[\*\]/' | \
    fzf -m --prompt="Install package: " \
        --preview 'echo {} | awk "{print \$2}" | xargs xq' \
        --preview-window=right:60%:wrap | \
    awk '{print $2}' | \
    xargs -ro sudo xbps-install -S
}

xrm() {
    xbps-query -m | \
    fzf --prompt="Remove package: " \
        --multi | \
    xargs -ro sudo xbps-remove -Rov
}
